server:
  port: 9006
spring:
  application:
    name: system
  datasource:
    url: jdbc:mysql://192.168.200.128:3306/changgou_system?useSSL=false&characterEncoding=UTF-8
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    prefer-ip-address: true

